import GithubIcon from "@/components/github-icon"
import { Toaster } from "@/components/ui/toaster"
import { UserProfile } from "@clerk/nextjs"
import { auth, currentUser } from "@clerk/nextjs/server"
import { ArrowLeft } from "lucide-react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Link from "next/link"
import "./globals.css"
import Providers from "./providers"
import UserDialog from "./user-dialog"
import { db } from "@/drizzle/db"
import { usage } from "@/drizzle/schema"
import { eq } from "drizzle-orm"
import { Button } from "@/components/ui/button"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const { userId } = auth()
    const user = await currentUser()
    const userCredits = user
        ? (
              await db.query.usage.findFirst({
                  columns: { credits: true },
                  where: eq(usage.userId, user.id),
              })
          )?.credits || 0
        : 0

    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <Toaster />
                    <div className="min-h-screen flex flex-col justify-between">
                        <header
                            className="sticky top-0 h-14 py-2 border-b w-full bg-background
                            flex justify-between items-center px-40 z-10"
                        >
                            <div className="flex gap-2 items-center">
                                <Button asChild variant={"link"}>
                                    <Link href="/">Generate</Link>
                                </Button>
                            </div>
                            <div className="flex gap-4 items-center">
                                <Button asChild variant={"link"}>
                                    <Link href="/buy-credits">
                                        {" "}
                                        Buy credits
                                    </Link>
                                </Button>
                                {userId && user ? (
                                    <UserDialog
                                        user={JSON.parse(JSON.stringify(user))}
                                        userCredits={userCredits}
                                    />
                                ) : (
                                    <>
                                        <Button asChild variant={"link"}>
                                            <Link href="/sign-in">Sign in</Link>
                                        </Button>
                                        <Button asChild variant={"link"}>
                                            <Link href="/sign-up">Sign up</Link>
                                        </Button>
                                    </>
                                )}
                            </div>
                        </header>
                        <div className="mx-40">{children}</div>
                        <footer
                            className="h-14 mt-10 border-t w-full 
                            flex items-center justify-between px-40"
                        >
                            <p>
                                <span className="opacity-85">Created by </span>
                                <Button asChild variant={"link"}>
                                    <Link
                                        target="_blank"
                                        href={"https://github.com/pimentellima"}
                                    >
                                        pimentellima
                                    </Link>
                                </Button>
                            </p>
                            <Button asChild variant={"link"}>
                                <Link
                                    target="_blank"
                                    href={
                                        "https://github.com/pimentellima/mock-ts-data-ai"
                                    }
                                >
                                    <GithubIcon className="w-10 h-10 fill-primary" />
                                </Link>
                            </Button>
                        </footer>
                    </div>
                </Providers>
            </body>
        </html>
    )
}
